-- LabourWelfare production schema for Supabase/PostgreSQL.
create extension if not exists pgcrypto;
create table if not exists users (id uuid primary key default gen_random_uuid(), role text not null check (role in ('customer','worker','admin')), name text not null, email text unique not null, phone text, password_hash text not null, location_label text, latitude double precision, longitude double precision, verified boolean default false, active boolean default true, created_at timestamptz default now());
create table if not exists service_categories (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, icon text);
create table if not exists services (id uuid primary key default gen_random_uuid(), category_id uuid references service_categories(id) on delete cascade, slug text unique not null, name text not null, keywords text[] default '{}');
create table if not exists worker_skills (worker_id uuid references users(id) on delete cascade, service_id uuid references services(id) on delete cascade, primary key (worker_id, service_id));
create table if not exists worker_locations (id bigserial primary key, worker_id uuid references users(id) on delete cascade, latitude double precision not null, longitude double precision not null, recorded_at timestamptz default now());
create table if not exists bookings (id uuid primary key default gen_random_uuid(), customer_id uuid references users(id), worker_id uuid references users(id), service_id uuid references services(id), description text, location_label text, latitude double precision, longitude double precision, requested_time timestamptz, status text not null default 'awaiting_worker', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists booking_attempts (id uuid primary key default gen_random_uuid(), booking_id uuid references bookings(id) on delete cascade, worker_id uuid references users(id), status text not null, reason text, sent_at timestamptz default now(), expires_at timestamptz, responded_at timestamptz);
create table if not exists reviews (id uuid primary key default gen_random_uuid(), booking_id uuid unique references bookings(id), customer_id uuid references users(id), worker_id uuid references users(id), rating integer check (rating between 1 and 5), feedback text, created_at timestamptz default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade, type text not null, title text not null, message text not null, data jsonb default '{}', read_at timestamptz, created_at timestamptz default now());
create table if not exists admin_actions (id uuid primary key default gen_random_uuid(), admin_id uuid references users(id), action text not null, target_id uuid, details jsonb default '{}', created_at timestamptz default now());
create index if not exists worker_location_geo_idx on worker_locations (worker_id, recorded_at desc);
create index if not exists booking_status_idx on bookings(status, created_at desc);
create index if not exists booking_attempt_lookup_idx on booking_attempts(booking_id, worker_id);
